#Exista un workflow (modify_readme.yml) con dos jobs que serán:
#Uno encargado de ejecutar los tests del proyecto como hicimos en la actividad pasada
#Otro que se ejecutará siempre tras el job anterior encargado de generar la modificación del readme y que tendrá los siguientes steps
#Uno encargado de obtener el código del repositorio actions/checkout@v2
#Otro encargado de llamar a nuestra action que genera el meme al que le pasaremos el resultado del job de ejecución de los tests
#Otro encargado de subir los cambios a git para que se actualicen los cambios del readme en el repositorio.

name: modify_readme
on:
  push:
    branches: github_actions_readme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
    
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
      - name: Instalar librerias
        run: npm install axios
      - name: Instalar api de memes
        run: npm install meme-generator
      - name: instalar dependencias de node 
        run: npm install node-fetch
      - name: Run tests
        run: npm test
      - name: Generate meme
        uses: ./
        with:
          result: ${{ job.status }}
      - name: Commit changes
        run: |
          git config --local user.email "
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: github_actions_readme


