# Path: .github\workflows\send_telegram_action.yml
name: send_telegram_action
description: 'Action para enviar mensajes a Telegram'
inputs:
  telegram_token:
    description: 'Token de Telegram'
    required: true
  telegram_chat_id:
    description: 'Id del chat de Telegram'
    required: true
  nombre:
    description: 'Nombre de la persona que se mostrará en el mensaje'
    required: true
runs:
  using: 'node12'
  main: 'index.js'



  