#Exista un workflow (modify_readme.yml) con dos jobs que serán:
#Uno encargado de ejecutar los tests del proyecto como hicimos en la actividad pasada
#Otro que se ejecutará siempre tras el job anterior encargado de generar la modificación del readme y que tendrá los siguientes steps
#Uno encargado de obtener el código del repositorio actions/checkout@v2
#Otro encargado de llamar a nuestra action que genera el meme al que le pasaremos el resultado del job de ejecución de los tests
#Otro encargado de subir los cambios a git para que se actualicen los cambios del readme en el repositorio.
on:
  push:
    branches:
            - github_action_readme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
     #version de node 16
      uses: actions/setup-node@v2
      with:
        node-version: '19'
    - run: npm install
