
name: 'Modify readme'
on:
  push:
    branches:
            - github_action_readme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
       #version de node 16
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - run: npm install
  test:
    runs-on: ubuntu-latest
    #version de node 16
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Install dependencies
        run: npm install
      - name: Install @actions/core
        run: npm install @actions/core
      - name: Install @actions/github
        run: npm install @actions/github
      - name: prepara el las variables de github
        run: echo "GITHUB_REPOSITORY=$(echo $GITHUB_REPOSITORY)" >> $GITHUB_ENV
  modify_readme:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install @actions/github
      run: npm install @actions/github
    - name: Generate meme
      uses: ./
    - name: Commit changes
      run: |
          git config --local user.email "borjaalventosa@gmail.com"
          git config --local user.name "borjeta"
          git add .
          git commit -m "Meme añadido al readme"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: github_action_readme
    
          

        


