on:
  push:
    branches:
      - nodejs_environment_job
jobs: 
  nodejs_environment_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting node version
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_environment_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
      - name: Run jest tests
        run: npm install jest &&  npm test
        env:
          CI: true
          DEFAULT_BRANCH: nodejs_environment_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: environment test execution
        uses: adeloyedeji/github-actions-hello@v1.0
        env:
          CI: true
          DEFAULT_BRANCH: nodejs_environment_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION_PERSON: '2DAW'
        with:
            who-to-greet: $jobs.nodejs_environment_job.env.DESTINATION_PERSON
      