#Sobre el repositorio creado en la actividad anterior y partiendo de la rama master, crea una nueva rama (react_app_deploy). Una vez hecho esto, deberás crear dentro de esta un proyecto react sencillo (el generado por el comando npx create-react-app sería suficiente). Dentro de esta rama, también habrá que crear un workflow (example_workflow) con las siguientes características:

#Dispondrá de dos jobs, uno encargado de la fase de construcción de los estáticos y otro encargado de hacer el despliegue de la aplicación en surge.sh (link). Se ejecutará al hacer un push sobre la rama creada y las características de sus jobs serán:
#Build job con 3 steps:
#Uno encargado de obtener el código del repositorio actions/checkout@v2
#Otro encargado de crear los estáticos. Ejecutará el comando npm install y npm run build
#Un tercer paso encargado subir los artefactos generados para actions/upload-artifact@v2  (ejemplos)
#Deploy job que siempre se ejecutará tras el job anterior con 2 steps:
#Un primero encargado de descargar los artifacts actions/download-artifact@v2
#Un segundo encargado de desplegar los artefactos descargados en surge dswistowski/surge-sh-action@v1 (link)

on:
  push:
    branches:
            - react_app_deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: build
    - name: Deploy
      uses: dswistowski/surge-sh-action@v1
      with:
        token: ${{ secrets.SURGE_TOKEN }}
        domain: ${{ secrets.SURGE_DOMAIN }}
        path: build
